In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

pd.set_option("display.max_columns", None)

In [3]:
df_combined_path = "../../../data/France/processed_data/combined_df.csv"
# df = pd.read_csv(df_path)
df = pd.read_csv(df_combined_path, low_memory=False)

# df["date"] = pd.to_datetime(df["date"])
# df.rename(
#     columns={
#         "territory_id": "route",
#         "territory_name": "route_name",
#         "Volume in Unit": "sales_quantity",
#         "Volume in Packs": "sales_amount",
#     },
#     inplace=True,
# )

In [4]:
df.head()

,data_type,source,Sales Date,Outlet SF ID,Store Participant Code,SKU SF ID,SKU Name,Brand Variant,Brand Family,Category,Volume in Unit,Volume in Packs,Ownership Type,Latitude,Longitude,Territory Id
0,sell_in,Logista,2026-01-05,0011t000011b5fiAAA,300003.0,a0U3W000002A7QeUAK,86195 - VELO ICE COOL 10MG,FR_BV_86195 - VELO ICE COOL 10MG,FR_BF_VELO,Oral,5,5.0,COCO,48.87946,2.32691,a0D1t000005iLAnEAM
1,sell_in,Logista,2026-01-05,0011t000011b5fiAAA,300003.0,a0U3W000002A7QtUAK,86196 - VELO ICE ALASKA 11MG,FR_BV_86196 - VELO ICE ALASKA 11MG,FR_BF_VELO,Oral,15,15.0,COCO,48.87946,2.32691,a0D1t000005iLAnEAM
2,sell_in,Logista,2026-01-05,0011t000011b5fiAAA,300003.0,a0UJz000005H9AVMA0,87571 - VELO ICE ALASKA 14MG,FR_BV_87571 - VELO ICE ALASKA 14MG,FR_BF_VELO,Oral,10,10.0,COCO,48.87946,2.32691,a0D1t000005iLAnEAM
3,sell_in,Logista,2026-01-05,0011t000011b5fiAAA,300003.0,a0UJz000009Ce1KMAS,VUSE POD2 CARTG 2/10 MJ 10 FRA M3,FR_BV_,FR_BF_,Vapour Liquids,5,5.0,COCO,48.87946,2.32691,a0D1t000005iLAnEAM
4,sell_in,Logista,2026-01-05,0011t000011b5fiAAA,300003.0,a0UJz000009CevlMAC,VUSE POD2 CARTG 2/10 PD 10 FRA NEW,FR_BV_,FR_BF_,Vapour Devices,5,6.0,COCO,48.87946,2.32691,a0D1t000005iLAnEAM

In [12]:
df[df["sku_code"] == "9999"]

Empty DataFrame
Columns: [date, customer_code, customer_name, latitude, longitude, route, route_name, channel_name, brand_name, category, sku_code, sales_quantity, sales_amount]
Index: []

In [4]:
print(df.shape)
df.head()

(664143, 13)

,date,customer_code,customer_name,latitude,longitude,route,route_name,channel_name,brand_name,category,sku_code,sales_quantity,sales_amount
0,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Devices,a0UJz000007USXVMA4,1,1
1,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Liquids,a0UJz000009CfTdMAK,1,1
2,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Liquids,a0UJz000009CfrpMAC,1,1
3,2026-02-01,307057.0,307057 - CAPRI (LE),48.89021,2.32111,a0D1t000005iLAnEAM,France_FRDiv_Reg1_AREA_A_SECTEUR_A_06,COCO,FR_BF_VELO,Oral,a0U3W000002A7QtUAK,80,4
4,2026-02-01,307057.0,307057 - CAPRI (LE),48.89021,2.32111,a0D1t000005iLAnEAM,France_FRDiv_Reg1_AREA_A_SECTEUR_A_06,COCO,FR_BF_VELO,Oral,a0UJz00000C50QHMAZ,1,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664143 entries, 0 to 664142
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            664143 non-null  datetime64[ns]
 1   customer_code   616956 non-null  float64
 2   customer_name   616956 non-null  object
 3   latitude        616956 non-null  float64
 4   longitude       616956 non-null  float64
 5   route           616956 non-null  object
 6   route_name      616956 non-null  object
 7   channel_name    615982 non-null  object
 8   brand_name      567919 non-null  object
 9   category        548501 non-null  object
 10  sku_code        567919 non-null  object
 11  sales_quantity  664143 non-null  int64
 12  sales_amount    664143 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(2), object(7)
memory usage: 65.9+ MB

In [12]:
total_sales_amount = df["sales_amount"].sum()

In [21]:
custormer_code_null_count = df["customer_code"].isnull().sum()
print(
    f"Number of null values in 'customer_code': {custormer_code_null_count}, which is {round(custormer_code_null_count/len(df)*100, 2)}% of the total records."
)
print(
    "The total sell for null customer code is: ",
    df[df["customer_code"].isnull()]["sales_amount"].sum(),
)
print(
    "Their sale is only: ",
    round(
        df[df["customer_code"].isnull()]["sales_amount"].sum()
        / total_sales_amount
        * 100,
        2,
    ),
    "%",
)

Number of null values in 'customer_code': 47187, which is 7.1% of the total records.
The total sell for null customer code is:  1051020
Their sale is only:  9.86 %

In [22]:
sku_code_null_count = df["sku_code"].isnull().sum()
print(
    f"Number of null values in 'sku_code': {sku_code_null_count}, which is {round(sku_code_null_count/len(df)*100, 2)}% of the total records."
)
print(
    "The total sell for null sku code is: ",
    df[df["sku_code"].isnull()]["sales_amount"].sum(),
)
print(
    "Their sale is only: ",
    round(
        df[df["sku_code"].isnull()]["sales_amount"].sum() / total_sales_amount * 100, 2
    ),
    "%",
)

Number of null values in 'sku_code': 96224, which is 14.49% of the total records.
The total sell for null sku code is:  8888671
Their sale is only:  83.37 %

In [ ]:
## Sell out ma kitne fisad dokanon ka 9999 araha ha.
## Also check koi ek provider ma araha ha.

## host

## sellout data corelation with rain data