In [22]:
import pandas as pd

pd.set_option("display.max_columns", None)
import numpy as np

import os, sys

sys.path.append(os.path.abspath(".."))

import original_data_work.helper_fn

importlib.reload(original_data_work.helper_fn)
from original_data_work.helper_fn import load_data

In [23]:
df_combined_path = "../../../data/France/processed_data/combined_df.csv"

df_sellin, df_sellout = load_data(df_combined_path)

In [24]:
df_path_sir_rizwan = "/home/asad/Desktop/FE2/sellout_data_sir_rizwan.csv"

sell_out_sr = pd.read_csv(df_path_sir_rizwan, low_memory=False)

In [25]:
df_sellout.shape, sell_out_sr.shape

((796387, 18), (796082, 11))

In [26]:
df_sellout.category.value_counts()

category
FMC               588131
Vapour Liquids     79384
RYO                36159
Oral               34374
Vapour Devices     21777
MYO                  501
Name: count, dtype: int64

In [60]:
sell_out_sr.head()

,Sales Date,POS,Outlet SF ID,City,SKU,SKU SF ID,RecordType,Volume in Unit,Volume in Packs,provider,month
0,20260101,304001,0011t000011b285AAA,PARIS,85279,a0U3W000000JDFIUA4,Trade SKU,1,1.0,Bimedia,Jan
1,20260101,304001,0011t000011b285AAA,PARIS,86195,a0U3W000002A7QeUAK,Trade SKU,20,1.0,Bimedia,Jan
2,20260101,304001,0011t000011b285AAA,PARIS,87571,a0UJz000005H9AVMA0,Trade SKU,1,1.0,Bimedia,Jan
3,20260101,304001,0011t000011b285AAA,PARIS,87791,a0UJz000008ZT4AMAW,Trade SKU,20,1.0,Bimedia,Jan
4,20260101,304001,0011t000011b285AAA,PARIS,87867,a0UJz000009CfrpMAC,Manufacturing SKU,1,1.0,Bimedia,Jan

In [61]:
sell_by_shop_sr = sell_out_sr.groupby("Outlet SF ID")["Volume in Packs"].sum()
# sell_out_sr.head()

In [62]:
sell_by_shop_hr = df_sellout.groupby("customer_code")["sales_quantity"].sum()

In [68]:
result = pd.DataFrame({"sell_sr": sell_by_shop_sr, "sell_hr": sell_by_shop_hr})

# Check equality
result["is_equal"] = result["sell_sr"] == result["sell_hr"]

# Difference (sr - hr)
result["difference"] = result["sell_sr"] - result["sell_hr"]

In [70]:
result.sort_values("difference", ascending=False).head()

                    sell_sr  sell_hr  is_equal  difference
0011t000011b2AhAAI   4449.0   4432.0     False        17.0
0011t000011b1lWAAQ   5499.0   5490.0     False         9.0
0011t000011b2BNAAY   4892.0   4884.0     False         8.0
0011t000011b1s7AAA   6081.0   6073.0     False         8.0
0011t000011b2hEAAQ  11987.0  11983.0     False         4.0

In [71]:
## Now see by sku code.

sell_by_sku_sr = sell_out_sr.groupby("SKU SF ID")["Volume in Packs"].sum()
sell_by_sku_hr = df_sellout.groupby("sku_code")["sales_quantity"].sum()

result = pd.DataFrame({"sell_sr": sell_by_sku_sr, "sell_hr": sell_by_sku_hr})

# Check equality
result["is_equal"] = result["sell_sr"] == result["sell_hr"]

# Difference (sr - hr)
result["difference"] = result["sell_sr"] - result["sell_hr"]

In [72]:
result.sort_values("difference", ascending=False).head()

                    sell_sr  sell_hr  is_equal  difference
a0U1t000002PXj3EAG      2.0      2.0      True         0.0
a0UJz000009CfYTMA0   1279.0   1279.0      True         0.0
a0UJz000009Cfv3MAC   3825.0   3825.0      True         0.0
a0UJz000009CfrpMAC  13989.0  13989.0      True         0.0
a0UJz000009CflNMAS   1301.0   1301.0      True         0.0