In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
df_sell_in = pd.read_csv("/home/asad/Desktop/footfall_explorer/data/France/processed_data/sell_in_merged.csv")

df_sell_out = pd.read_csv("/home/asad/Desktop/footfall_explorer/data/France/processed_data/sell_out_merged.csv")

/tmp/ipykernel_23205/2697493990.py:1: DtypeWarning: Columns (3,4,5,6,9,10,11,12,25,26,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sell_in = pd.read_csv("/home/asad/Desktop/footfall_explorer/data/France/processed_data/sell_in_merged.csv")

In [3]:
df_sell_in.shape, df_sell_out.shape

((122307, 34), (664143, 13))

In [4]:
df_sell_in.head()

,date,outlet_sf_id,sku_code,sku_code.1,sku_sf_id,sku_sf_id.1,record_type,sales_quantity,sales_amount,sku_sf_id.2,...,sku_code.2,sku_code.3,sku_name,brand_variant,brand_variant_code,brand_name,brand_code,category,invoice_code,sec
0,2026-01-05,0011t000011b5fiAAA,86195,a0U3W000002A7QeUAK,NaN,NaN,NaN,5,1,NaN,...,86195,a0U3W000002A7QeUAK,86195 - VELO ICE COOL 10MG,FR_BV_86195 - VELO ICE COOL 10MG,a0S3W0000059gGrUAI,FR_BF_VELO,a0S3W0000059fx7UAA,Oral,202601050001,E
1,2026-01-05,0011t000011bCJaAAM,85548,a0U3W000002BYaXUAW,NaN,NaN,NaN,800,4,NaN,...,85548,a0U3W000002BYaXUAW,85548 - VOGUE Lâ€™ORIGINALE VERTE ICE 20s,FR_BV_85548 - VOGUE Lâ€™ORIGINALE VERTE ICE 20s,a0S3W000004d6FSUAY,FR_BF_VOGUE,a0S1t000002esMyEAI,FMC,202601050002,B
2,2026-01-05,0011t000011bCJaAAM,86175,a0U3W000002BYagUAG,NaN,NaN,NaN,200,1,NaN,...,86175,a0U3W000002BYagUAG,86175 - LUCKY STRIKE ICE LONGUES 20s,FR_BV_86175 - LUCKY STRIKE ICE LONGUES 20s,a0S3W000004d6FWUAY,FR_BF_LUCKY STRIKE,a0S1t000002esHkEAI,FMC,202601050003,E
3,2026-01-05,0011t000011bCJaAAM,99999,NaN,NaN,NaN,NaN,0,0,NaN,...,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202601050004,E
4,2026-01-05,0011t000011bCJaAAM,99999,NaN,NaN,NaN,NaN,6440,32,NaN,...,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202601050005,A

In [6]:
df_sell_out.head()

,date,customer_code,customer_name,latitude,longitude,territory_id,territory_name,channel_name,brand_name,category,sku_code,Volume in Unit,Volume in Packs
0,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Devices,a0UJz000007USXVMA4,1,1
1,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Liquids,a0UJz000009CfTdMAK,1,1
2,2026-02-01,576579.0,576579 - TABAC,48.86806,2.35239,a0D1t000005iLAGEA2,France_FRDiv_Reg1_AREA_A_SECTEUR_A_01,Independent,FR_BF_,Vapour Liquids,a0UJz000009CfrpMAC,1,1
3,2026-02-01,307057.0,307057 - CAPRI (LE),48.89021,2.32111,a0D1t000005iLAnEAM,France_FRDiv_Reg1_AREA_A_SECTEUR_A_06,COCO,FR_BF_VELO,Oral,a0U3W000002A7QtUAK,80,4
4,2026-02-01,307057.0,307057 - CAPRI (LE),48.89021,2.32111,a0D1t000005iLAnEAM,France_FRDiv_Reg1_AREA_A_SECTEUR_A_06,COCO,FR_BF_VELO,Oral,a0UJz00000C50QHMAZ,1,1

In [7]:
si = df_sell_in.copy()
so = df_sell_out.copy()